version: "3.7"

x-app-defauls: &app-defaults
  restart: unless-stopped
  image: c1oudgg/notifyo:latest
  
  ports:
    - "3000:3000"
  networks:
    - notifyo
  environment:
    - TZ=Etc/UTC
    - MONGODB_URL=mongodb://admin:pass@localhost:27017/notifyo

x-db-defaults: &db-defaults
  image: mongo
  restart: always
  ports:
    - 27017:27017

services:
  app:
    <<: *app-defaults
    container_name: notifyo_app
    depends_on:
      - db
    volumes:
      - ./config.toml:/app/config.toml
      - ./internal:/app
    networks:
      - notifyo

  db:
    <<: *db-defaults
    container_name: notifyo_db
    command: mongod --quiet
    volumes:
      - ./data/db:/data/db
    networks:
      - notifyo

networks:
  notifyo:
    driver: bridge

volumes:
  notifyo-data: